### ISSUE TITLE
Remove data for completed applications

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#10]
When an application process is completed i.e. funds have been disbursed to the MSME by the FI, I want the data for the application to only be viewable for one week after the completion date-time, so that this personal data is not stored by the OCP long term.

- We still want to keep the metadata that is required for the FI and OCP dashboard, but this should not mean we need to store personal data

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=443-3219&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Some notes on this:

- All the uploaded documents by the MSME must be deleted as part of this
- We don't want to delete the application information or the MSME row (so we can calculate if the same MSME has been credited multiple times using Credere)

So, the proposal is to:

- Add a hashed id column in the MSME table using the MSME identifier 
- Add a hashed id column in the application table using the MSME identifier and the award identifier
- When deleting personal information:
  - Delete all the uploaded documents
  - Remove the legal identifier and name from the MSME table
  - Delete all the awards (and historical contracts) from the award table. Note that the award_id foreign key in the application table must be nullable.

When we check for a new awarded MSME:
- Use the same hashing algorithm to check if this MSME already has a row in the MSME table, if so, then refill the name and identifier columns and
- To avoid emailing the same MSME for the same award, use the same hashing algorithm with the MSME identifier and award identifier to check if that already exists in the application table. If it exists, then ignore the award as it has been processed already, if not, proceed as usual.

cc @jpmckinney

**Comment by jpmckinney** [comment]
For context, the most sensitive private information is the documents, as these might contain financial information, personal data, etc. – and they are not generally available. Thankfully, deleting these is easy.

Names, identifiers, emails, etc. are less sensitive as they are generally available (unless they were manually entered by FIs or OCP).

If the proposal above will take long to implement, then we can learn more from the lawyers to see if it can be relaxed. For now, it follows our original requirements.

**Comment by yolile** [comment]
Closing in favor of #141
