### ISSUE TITLE
Access funds upon contract being signed

### ISSUE THREAD

**Issue by nahu** [open-contracting/credere-backend#107]
When I receive my application approved email, I want further instructions for what to do when the contract with the buyer is signed, so that I can access the funds when my business is ready to start fulfilling the contract.

- Instructions to be included in the application approved notification email including a temporary link to access Credere
- MSME to upload contact via the UI
- FI to review and disburse funds and mark in UI

Email template: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=199-1619&mode=design&t=Dh1uDL7BC1eOr04K-4

For the link in the mail use the same pattern from other and enpoint in front end is upload-contract

**Comment by yolile** [comment]
Closing as completed
