### ISSUE TITLE
Declined application further options

### ISSUE THREAD

**Issue by nahu** [open-contracting/credere-backend#108]
When my application for credit is declined, I want to see what other options are available for me to apply for credit for, so that I can still try to access credit from another credit provider.

- User to receive declined application email notification
- User to be able to select “Find alternative credit” button
- User to be shown other options available to them - removing the provider (and all options by them) the  user has been declined by
- Users are only offered additional options in email notification IF there are alternative options in Credere available, ELSE user only receives declined email without “Find alternative credit” button.

Email template: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=201-1723&mode=design&t=Dh1uDL7BC1eOr04K-4

**Comment by yolile** [comment]
Closed as implemented
