### ISSUE TITLE
FI settings in Credere

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#11]
When I log into Credere as an OCP admin, I want to be able to see all of the FIs set up in the system, to be able to edit the settings for an existing FI and to be able to add a new FI so that this does not have to be done in the code.

- Actions on this screen are edit (existing FI) and add new FI

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=447-2666&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=448-2816&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closing as completed
