### ISSUE TITLE
Edit existing FI settings

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#12]
When I select ‘edit’ for an existing FI, I want to be able to edit specific settings that may be requested by the FI. The previously inputted data needs to be visible for me to edit.

- Change FI name as it appears to the MSME
- Change FI type (options are: Commercial Bank, FinTech, Government Bank)
- Size of MSMEs FI is willing to lend to (options are: Micro, Small, Medium)
- Range of credit amounts for different sizes of SMEs (only appears of the size of MSME is selected)
- Change the values for the calculator rules for an FI
- SLA agreement i.e. time frame agreed to process and application
- SLA time frame to disburse funds after contract uploaded by MSME

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=447-2666&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=448-2816&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closing as completed
