### ISSUE TITLE
Add new FI

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#13]
When I select ‘add new credit provider’ I want the form to appear for me to provide the following data to set up a new FI on the system.

- FI name as it is to appear to MSME in the tool
- FI type (options are: Commercial Bank, FinTech, Government Bank)
- Size of MSMEs FI is willing to lend to (options are: Micro, Small, Medium)
- Range of credit amounts for different sizes of SMEs (only appears of the size of MSME is selected)
- Change the values for the calculator rules for an FI
- SLA agreement i.e. time frame agreed to process and application
- SLA time frame to disburse funds after contract uploaded by MSME

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=447-2666&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=448-2816&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
@nahu, the last item is missing in the FI form:

> SLA time frame to disburse funds after contract uploaded by MSME

But we can leave that outside the MVP
