### ISSUE TITLE
Email notification for new MSME application

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#16]
When an MSME submits an application, I want to receive an email to notify me with a link to the login screen for Credere. so I can start to process the application.

- Email to be sent to a group email address for the FI selected by the MSME
- No data for the MSME or their application to be included in the email content
- Team at FI to arrange themselves how the application is processed
- [ ] Send overdue reminder if past SLA time frame

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=424-2388&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=440-2492&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
The last item hasn't been implemented yet but closing this one in favor of #7
