### ISSUE TITLE
Decide on alternative way to track skipped awards, instead of cron job emails

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#182]

**Comment by yolile** [comment]
One option could be to log this into a table. Some existing tables that we could reuse are `message` and `application_action`, however using any of them sounds like an overuse of their purpose. So maybe we should just create a new table where we record any errors that happened while sending the first email to MSMEs. The columns could be date, error type, source_data (JSONB), and source URL. Depending on the error type, the source data may be different (e.g. depending on the source URL that failed). 

If we want, we could set up a process that emails us at the end of the day with the failures of the day.

**Comment by jpmckinney** [comment]
Yes, sounds good. Maybe name the model EventLog (technically it's an "event log message", but we'll only ever have one "log", so whatever) and change "error type" to "category" (like in Python's log module) or something – since skipped awards aren't errors, they're just something we care to track.

So, EventLog:

- category (str not null)
- data (jsonb not null, default dict)
- url (str not null, default empty)
- created_at (auto)

Can consider a "message" column, as "skipped award" is raised in many locations, and we might want to differentiate them with some sort of label in the message column.
