### ISSUE TITLE
Remove contract upload process (CONTRACT_UPLOADED and COMPLETED status)

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#186]
Right now, in Credere, for FIs, we only have one "approval" step and then only the option to put the amount granted. But now, we found out that they are not allowed to approve or even say they are pre-approving a credit through Credere.  We also learned that after reviewing the documents and application sent through Credere, the FI still need to ask for more documents and internal process before approving or denying the credit. 
For the pilot, our workaround is to: 
- Edit the "approval" email text (https://github.com/open-contracting/credere-backend/commit/17a68405d27d9a1c78ba1f41faebd8b00ed12551) to indicate that only the documents were reviewed but there is still an onboarding to do with the FI directly. 
- After the application has been "approved" via Credere, but then the internal processes and reviews fail and they have to reject the application, ask FIs to put "0" as the amount granted and not send any more emails to the MSMEs, as the FI is communicating with the MSME directly anyway. (to be implemented)

In the future, we should implement a pre-approval step fully in Credere and remove this workaround.

**Comment by yolile** [comment]
For the second point, I've included the "Reject" button at the contract review stage instead (https://github.com/open-contracting/credere-frontend/commit/9bae880b80b84614f9dabe4e7d95e18e945fe873), to avoid having incorrect statistics around the number of approvals, etc. For future applications, we ask FI to only click "approve" if they have completed their internal checks and onboarding process as well.

**Comment by yolile** [comment]
Update: to have this in place we will remove the "contract upload" logic, so we will only have preapproved and then, either approved or rejected. More details TBD @sebasdocp

**Comment by yolile** [comment]
The new suggested flow is:

PENDING->ACCEPTED->SUBMITTED->APPROVED->COMPLETED/REJECTED

Without having CONTRACT_UPLOADED between APPROVED and COMPLETED/REJECTED

We could remove CONTRACT_UPLOADED entirely and update all the associated logic in the front end and the back end. Or, we could change the backend to set the application from SUBMITTED to CONTRACT_UPLOADED (and remove "APPROVED") and have less logic to change in the front and the back end. The second option is simpler but messier (e.g. it would be confusing to pass for SUBMITTED to CONTRACT_UPLOADED)

@jpmckinney any thoughts?

**Comment by yolile** [comment]
If we want to do this right, I would change "APPROVED" to "PRE-APPROVED" and "COMPLETED" to "APPROVED", and delete "CONTRACT_UPLOADED". This requires even more changes but maybe it is better to do it all right for once.

**Comment by jpmckinney** [comment]
Keep in mind that we can change the enum without changing the database value, e.g. `PRE_APPROVED = i("APPROVED")`, which would simplify the changes, though it will make the translations and DB a bit odd. But, we don't look at the translations or the DB frequently.

I would be in favor of at least changing the enums. I also don't like the "SUBMITTED to CONTRACT_UPLOADED" alternative, because it's more of a hack and it's easier to miss a change or get confused.

If we do change the DB values, we need to write the migrations carefully, e.g. run APPROVED -> PRE_APPROVED first, not COMPLETED -> APPROVED first (and make sure that if the first rename fails then it causes an error that prevents the second rename from running).

**Comment by yolile** [comment]
After thinking about it more, and talking with FIs and Sebastián, the final proposal is to:

- Remove CONTRACT_UPLOADED and COMPLETED status. COMPLETED only made sense if a previous CONTRACT_UPLOADED status was needed. Without it, we don't need a "COMPLETED" status anymore.
- Do not have a pre-approved status. The FIs will approve or reject when they know their final decision (e.g. when they indeed have done all their internal processes). The application therefore will remain "STARTED" (reflecting that the FI is processing the application) until they reach a decision

So the new flow is even simpler:

PENDING->ACCEPTED->SUBMITTED->STARTED->APPROVED/REJECTED

For the migrations, we will need to change APPROVED and CONTRACT_UPLOADED to STARTED and COMPLETED to APPROVED.

**Comment by jpmckinney** [comment]
Ok, so new state is:

![image](https://github.com/user-attachments/assets/83f07f18-59d6-4138-a609-86ed4d8b5491)

<details>

```
PENDING -> LAPSED: borrower doesn't accept or decline the invitation
PENDING -> DECLINED: borrower declines the invitation
PENDING -> ACCEPTED: borrower accepts the invitation
ACCEPTED -> LAPSED: borrower doesn't submit the application
ACCEPTED -> SUBMITTED: borrower submits the application
SUBMITTED -> STARTED: lender starts reviewing the application
STARTED -> INFORMATION_REQUESTED: lender requests the borrower to update a document
STARTED -> REJECTED: lender rejects the application
STARTED -> APPROVED: lender approves the application
INFORMATION_REQUESTED -> LAPSED: borrower doesn't submit the information requested
INFORMATION_REQUESTED -> STARTED: borrower updates the document
```

</details>

**Comment by jpmckinney** [comment]
> For the migrations, we will need to change APPROVED and CONTRACT_UPLOADED to STARTED and COMPLETED to APPROVED.

You mean in terms of how we modify existing applications to match the new logic? (For future applications or applications in earlier states, I agree there is nothing to do.)

If any borrowers are presently in APPROVED, they will have received an email asking them to do stuff that is no longer needed (and where the pages might not exist anymore). Looks like we have 74 APPROVED. Wouldn't we need special logic to handle this (e.g. at email saying they no longer have anything to do?)

**Comment by yolile** [comment]
> If any borrowers are presently in APPROVED, they will have received an email asking them to do stuff that is no longer needed (and where the pages might not exist anymore). Looks like we have 74 APPROVED. Wouldn't we need special logic to handle this (e.g. at email saying they no longer have anything to do?)

You are right, we should prepare an email and (manually) send it to whatever applications are APPROVED when these changes are ready and deployed

**Comment by yolile** [comment]
We will also need to set `lender_approved_at = lender_completed_at`

**Comment by jpmckinney** [comment]
Yes, and to avoid ambiguity: First set it to null (for those currently only with status of approved) then set to completed_at (if status is completed)

**Comment by jpmckinney** [comment]
Sounds good. For those currently only approved, this will correctly set approved_at to null.

**Comment by yolile** [comment]
We will also delete the MessageTypes CONTRACT_UPLOAD_REQUEST, CONTRACT_UPLOAD_CONFIRMATION, CONTRACT_UPLOAD_CONFIRMATION_TO_FI, CREDIT_DISBURSED.

That means we must delete the existing message that uses any of these statuses. I don't think we actually care about messages, but, if we want, we could update CREDIT_DISBURSED to APPROVED, but I don't think it is worth the effort

**Comment by yolile** [comment]
And the same for the `ApplicationActionType` `FI_COMPLETE_APPLICATION` (and `MSME_UPLOAD_CONTRACT`) statuses

**Comment by jpmckinney** [comment]
Does the code ever query for existing MessageType or ApplicationActionType? If so, maybe better to migrate these to be consistent with future approvals.

**Comment by yolile** [comment]
`ApplicationActionType`: only to calculate `days_waiting_for_lender` and `get_modified_data_fields` (but FI_COMPLETE_APPLICATION is not queried)

`MessageType`:  to send emails (but we need to update the logic there anyway).

So I don't think we need to migrate them

**Comment by yolile** [comment]
But if we do, I guess we will need to:
- Delete APPROVED_APPLICATION messages
- Update CREDIT_DISBURSED to APPROVED_APPLICATION
- Delete APPROVED_APPLICATION actions
- Update FI_COMPLETE_APPLICATION to APPROVED_APPLICATION

**Comment by jpmckinney** [comment]
It's similar logic to our other migrations, so might as well?

**Comment by yolile** [comment]
Note that as part of this, all the `SIGNED_CONTRACT` logic is also removed, and `SIGNED_CONTRACT` is now a regular document type.

**Comment by yolile** [comment]
> For the migrations, we will need to change APPROVED and CONTRACT_UPLOADED to STARTED

Actually, I think that we should instead change these two to SUBMITTED again so that the send_onboarding_reminder logic takes them and asks for the onboarding process. The other option is to leave the migration as it is and change it back to SUBMITTED manually only for the applications to the lender with an external onboarding process.

**Comment by jpmckinney** [comment]
> > For the migrations, we will need to change APPROVED and CONTRACT_UPLOADED to STARTED
> 
> Actually, I think that we should instead change these two to SUBMITTED again so that the send_onboarding_reminder logic takes them and asks for the onboarding process.

> The other option is to leave the migration as it is and change it back to SUBMITTED manually only for the applications to the lender with an external onboarding process.

I don't think we want to "undo" a lender STARTing an application, especially if they don't have an onboarding process.

I think maybe a better solution is:

1. Turn off send-reminders cron temporarily.
2. Add a command to "catch up" on missing emails. This command can have the special logic that we intend to remove in #439.
3. Run that command.
4. Commit the "correct" logic.
5. Deploy the correct logic and turn on send-reminders cron.

This way, we don't have any "hack" code in the app. All the hack code goes in a one-time command.

**Comment by yolile** [comment]
> I don't think we want to "undo" a lender STARTing an application, especially if they don't have an onboarding process.
>This way, we don't have any "hack" code in the app. All the hack code goes in a one-time command.

To clarify, my second suggestion was to keep everything as it is, and then, manually (from the database) update the applications to a lender with external onboarding only back to SUBMITTED, and then run the send_reminders command as usual

> Add a command to "catch up" on missing emails. 

E.g. to send emails to all the STARTED and SUBMITTED applications (after the migration is run) which don't have the borrower_accessed_external_onboarding set?

I guess we can add that command and leave it there as a separate, manual-only command
