### ISSUE TITLE
Ignoring expected "0 awards from ..."  cases

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#192]
My suspicion is that the API returns procedures where no award has been made (i.e. process is unsuccessful).

If we can skip these, the cron emails will be more relevant.

I don't know how best to determine this, but, for example, looking at https://www.datos.gov.co/resource/p6dx-8zbt.json?$where=id_del_portafolio=%27CO1.BDOS.5096680%27 (i.e. removing `%20AND%20nombre_del_proveedor=%27OKORUM%20TECHNOLOGIES%20SAS%27`), I can see some things like:

Can also see at https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.5111621&isFromPublicArea=True&isModal=true&asPopupView=true

Lots of "No ...":

```
    "adjudicado": "No",
    "id_adjudicacion": "No Adjudicado",
    "codigoproveedor": "No Adjudicado",
    "departamento_proveedor": "No aplica",
    "ciudad_proveedor": "No aplica",
    "nombre_del_adjudicador": "No Adjudicado",
    "nombre_del_proveedor": "No Adjudicado",
    "nit_del_proveedor_adjudicado": "No Adjudicado",
```

Though some without "No":

```
    "fase": "Presentación de oferta",
    "estado_del_procedimiento": "Adjudicado",
    "estadoresumen": "Adjudicado"
```

Lots of zeroes:

```
    "proveedores_invitados": "0",
    "proveedores_con_invitacion": "0",
    "visualizaciones_del": "0",
    "proveedores_que_manifestaron": "0",
    "respuestas_al_procedimiento": "0",
    "respuestas_externas": "0",
    "conteo_de_respuestas_a_ofertas": "0",
    "proveedores_unicos_con": "0",
    "numero_de_lotes": "0",
    "valor_total_adjudicacion": "0",
```

**Comment by yolile** [comment]
I think this is a source data quality issue or consistency problem. We use the contracts data set (https://www.datos.gov.co/resource/jbjy-vk9h.json) as the main/first data source, as the parties' scale info is there. For this example, the supplier name is available here: https://www.datos.gov.co/resource/jbjy-vk9h.json?$where=proceso_de_compra=%27CO1.BDOS.5096680%27, but then, we need to query https://www.datos.gov.co/resource/p6dx-8zbt.json to get the more info about the award. In cases where the info is available in the contracts data set but not in the awards data set we will have this issue.

**Comment by jpmckinney** [comment]
Aha. And I see we need `nombre_del_proveedor` in addition to `id_del_portafolio`, because, for example, https://www.datos.gov.co/resource/p6dx-8zbt.json?$where=id_del_portafolio=%27CO1.BDOS.5009675%27 returns 7 results, with different `nombre_del_proveedor` ("MODERLINE SAS" appears 3 times).

What if, in the case where it's 0, we try with `nombre_del_proveedor='No Adjudicado'`? It looks like these will be correct:

* nombre_del_procedimiento (title)
* descripci_n_del_procedimiento (description)
* estado_del_procedimiento (contract_status) ("Adjudicado")

`award_date` will be unavailable, but that seems to be acceptable by the code.

**Comment by jpmckinney** [comment]
Also, in the case where there are multiple awards returned, for that example above, it looks like the only changes are to `id_adjudicacion` and `valor_total_adjudicacion`, which we don't care about.

So, the logic in that case can be to check whether the values we extract are all unique. For example, extract a 4-tuple into a set, and if  the set has size 1, then use it (and store one of the results as the `source_data_awards`).

**Comment by yolile** [comment]
Good ideas! I will try them both and see if it makes sense to use these approaches
