### ISSUE TITLE
"PENDING" applications without a primary_email

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#197]
related to #191
There are some applications with "PENDING" status that don't have a primary_email set. This shouldn't happen, as the logic is that if the MSME email is not available the application is not created. We need to check why and how this is happening. 

----

Can also:

* [x] Rename `create_new_borrower` to `get_borrower`
* [x] Restore `is_valid_email` to previous, simpler version when closing this issue, viz https://github.com/open-contracting/credere-backend/issues/191#issuecomment-1791556868
* [x] Remove the guard added in e793eaf5cfa2942629c0aedc32473b167be03e33

**Comment by jpmckinney** [comment]
Another possibility is if the application is updated, but an empty primary_email is not omitted (e.g. with `jsonable_encoder(payload, exclude_unset=True)`). It looks like we only use the full payload to perform an update for the application's award and borrower (`update_application_award`, `update_application_borrower`), but we use `exclude_unset=True` here, in any case.

I tried checking for any other clues by looking for application actions for these pending applications without emails, but, unsurprisingly, they have no actions.

```sql
SELECT aa.*
FROM application_action aa
INNER JOIN application a ON a.id = aa.application_id
WHERE primary_email = ''
    AND status NOT IN ('LAPSED', 'COMPLETED', 'DECLINED', 'REJECTED');
```

**Comment by jpmckinney** [comment]
Okay, another possibility: the fetch-awards command is run at 14:00 UTC and remove-dated-application-data is run at 02:00 UTC. As described above, fetch-awards will create or update borrowers. remove-dated-application-data will set a borrower's email to '' **if there are no other unarchived applications for the same award**.

However, shouldn't this logic be: if there are no other unarchived applications for the same **borrower**?

**Comment by jpmckinney** [comment]
To rule another possibility out:

* Let's say `remove-dated-application-data` emptied a borrower's email some time in the past.
* `_get_or_create_borrower` updates the borrower. Prior to the recent fafbe0f5, it also called `session.refresh`. This could lead to the types of issues discussed [here](https://docs.sqlalchemy.org/en/20/faq/sessions.html#faq-session-identity), [here](https://docs.sqlalchemy.org/en/20/orm/session_state_management.html#session-expire) and [here](https://docs.sqlalchemy.org/en/20/orm/session_basics.html#expiring-refreshing). The `update` call will effectively do `setattr(borrower, "email", "non-empty value")`, so – unless there is something funky going on with getters and setters – then `borrower.email` should return the same non-empty value. I think nothing weird is going on:

```
from app.models import Borrower
from unittest.mock import MagicMock

b = Borrower()
setattr(b, "email", "x")
b.email
# 'x'

b.update(MagicMock(), email="y")
b.email
# 'y'
```

**Comment by jpmckinney** [comment]
Ruling out another possibility: `background_tasks.add_task` is never used to call a function relevant to this issue.

Other facts:

* The message about empty emails occurs in fetch-awards and send-reminders.
* `fetch_new_awards_from_date` calls `mail.send_invitation_email` in the same transaction that sets `borrower.email`.
* send-reminders calls `mail.send_mail_intro_reminder` using `application.primary_email`.

I think the next steps would be to re-play the past Sentry errors: https://open-contracting-partnership.sentry.io/issues/4595776359/?project=4505799907672064&referrer=github_integration

If we learn nothing, then we should revert #191, because the fix in #191 is just preventing errors from being reported to Sentry, where we have a change of debugging them.

**Comment by yolile** [comment]
> Okay, another possibility: the fetch-awards command is run at 14:00 UTC and remove-dated-application-data is run at 02:00 UTC. As described above, fetch-awards will create or update borrowers. remove-dated-application-data will set a borrower's email to '' if there are no other unarchived applications for the same awa


For all the borrowers with this issue, their updated_at is at 02:00 UTC, and the difference with their created_at is always (but for one record) 21 days. 
for the applications with this issue, their created_at is, as expected, at 14:00 UTC, **BUT their updated_at is always earlier by around a minute!**

**Comment by yolile** [comment]
All the borrower.created_at are much before (>30 days) their award.created_at and their application.created_at (award.created_at and application.created_at around the same time)

**Comment by yolile** [comment]
> _get_or_create_borrower updates the borrower. Prior to the recent https://github.com/open-contracting/credere-backend/commit/fafbe0f5b74e162bc8bef0bf49b11d7ff7a62da2, it also called session.refresh. This could lead to the types of issues discussed [here](https://docs.sqlalchemy.org/en/20/faq/sessions.html#faq-session-identity), [here](https://docs.sqlalchemy.org/en/20/orm/session_state_management.html#session-expire) and [here](https://docs.sqlalchemy.org/en/20/orm/session_basics.html#expiring-refreshing).

Let's see if that and #231 fix the issue. I will deploy all of the changes now and we should monitor if this happens again in the future

**Comment by jpmckinney** [comment]
```
SELECT borrower_id FROM application WHERE status = 'PENDING' AND primary_email = '';
```

Returns 0 results. You can maybe have a reminder to check again sometime in the future, but closing the issue as resolved.
