### ISSUE TITLE
List of MSME applications (FI User)

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#20]
When I log into the Credere UI, I want to see a list of all of the MSME applications made to my organization, so that I can get an overview of how many applications need processing to be completed, when they were submitted, which stage they are at and who is processing it.

- User can also go into the application to view or continue processing it
- Application processing is not tied to the user that started to process it
- User can ONLY see applications that belong to their FI
- User also able to download the application (we need to clarify this with FIs)
- User can sort columns as per UI design

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=104-51&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closing as completed
