### ISSUE TITLE
Check whether flush() is actually needed

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#206]
I think we autoflush: https://docs.sqlalchemy.org/en/20/orm/session_basics.html#session-flushing

Maybe needed for: https://stackoverflow.com/a/61970135

**Comment by yolile** [comment]
We set `autoflush=False` https://github.com/open-contracting/credere-backend/blob/709dab6abdd0217dfcd9d87b51aa7bd9607777c2/app/db.py#L16

**Comment by jpmckinney** [comment]
Do you know why?

**Comment by yolile** [comment]
No...
