### ISSUE TITLE
Double-check authorization and workflow logic

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#207]
- /applications/{id}/download-application/{lang} (`download_application`) doesn't perform authorization (e.g. that the lender is authorized to download the application). This most likely is a bug.
- /applications/submit (`update_apps_send_notifications`) doesn't check if the application is expired.

The following don't check the application's status:

- /applications/upload-document (`upload_document`)
- /applications/{id}/reject-application (`reject_application`)
- /applications/{id}/upload-compliance (`upload_compliance`)

The variable is named `OCP_cannot_modify` (now `OCP_CAN_MODIFY`), but it applies to the FIs (lenders) as well.

**Comment by yolile** [comment]
> /applications/upload-document (upload_document)

This one doesn't check the status but it checks the `application.pending_documents` field, which is only True when the application is  INFORMATION_REQUESTED, or when copying the documents from a previous application for the same award (`confirm_credit_product`)

But maybe it is worth opening another issue to decide if we need that field at all.
