### ISSUE TITLE
Stages for application processing

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#21]
When I log into the Credere UI, I want to see a list of all of the MSME applications made and the different stages that they are at so that I can prioritize applications accordingly.
Stages as follows:

- Submitted - the application has been received but processing by a team member has verified 0 pieces of data (includes if an OCP team member has made updates to missing data)
- In progress - FI team member has verified 1+ piece of data, but is not waiting for a response from the MSME
- Awaiting information - a FI team member has sent an email through the Credere system and not yet received a response
- Approved - a team member at the FI has approved the MSME’s application for credit
- Rejected - a team member at the FI has rejected the MSME’s application for credit
- Contract uploaded - the MSME has uploaded their signed contract
- Completed - the FI has marked the application as closed after funds disbursed

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=104-51&t=ZGzh5x7zMAwvmP8g-4

**Comment by jpmckinney** [comment]
Related #39
