### ISSUE TITLE
login_mfa should probably error if "ChallengeName" not in response

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#214]
`raise NotImplementedError` should be fine, as this code should be unreachable.

**Comment by jpmckinney** [comment]
login_mfa has a separate issue where if neither condition in the `except` block is true, it just doesn't return anything.

**Comment by yolile** [comment]
> login_mfa has a separate issue where if neither condition in the except block is true, it just doesn't return anything.

I think we could do 

```` python
        if e.response["Error"]["Code"] == "ExpiredTemporaryPasswordException":
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Temporal password is expired, please request a new one",
            )

        else:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail=e.response["Error"]["Message"],
            )
````

Because I think the response object will always have `["Error"]["Message"]`

**Comment by jpmckinney** [comment]
I think so. You can put a link to `https://boto3.amazonaws.com/v1/documentation/api/latest/guide/error-handling.html#parsing-error-responses-and-catching-exceptions-from-aws-services` above the if-statement.
