### ISSUE TITLE
Review and verify MSME information (stage 1)

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#22]
When I am processing a MSME application in Credere, I want to be able to review basic information for the MSME manually, add or update information (e.g. the MSME address which might be incomplete), check any details for the MSME directly in SECOP II and mark in the system that everything has been manually verified, so that the FI I work for can be confident that the process has been followed correctly.

- Link to each MSME profile in SECOP II directly
- Verify each data field individually using toggle switch
- Fields where data is missing to have an expand feature for the user to view more information and guidance on how to proceed
- Fields where data is missing or incomplete to have the option for the user to add or edit manually
- User is not allowed to proceed if there are empty data fields
- User is not allowed to proceed if one or more toggle switches are set to ‘No’

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=105-581&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=159-1667&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=161-1949&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closing as completed
