### ISSUE TITLE
Review and verify MSME bank information and documents (stage 2)

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#23]
When I am processing an MSME application in Credere, I want to be able to review information and documents provided by the MSME manually, opening documents to review them, emailing MSMEs directly if there are any issues and mark in the system that everything has been manually verified so that the FI I work for can be confident that the process has been followed correctly.

- User to be able to click a link to open a message box in the tool 
- Verify each data field individually using toggle switch
- User is not allowed to proceed if one or more toggle switches are set to ‘No’

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=107-108&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=558-3790&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=558-3789&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closing as completed
