### ISSUE TITLE
MSME - allow direct applications

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#245]
From Strive: Is there a version of the tool where a MSE could upload a contract they've won with a public org and request funding through the platform to fulfil it (e.g. if the public org is not yet signed up to OCP)? Just wondering whether some associations would be more interested to share if it was a route for MSEs with contracts over X value to access capital, essentially making it a hub for small business finance.

**Comment by jpmckinney** [comment]
Closing as an old idea that I don't think will be effective (would require massive awareness campaign).
