### ISSUE TITLE
Replace transaction_session with rollback_on_error

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#249]
This mostly means having an explicit `session.commit()` in the current `transaction_session` blocks.

This will avoid errors in future, if we need to return a committed instance, as we'd just add `session.refresh(instance)` or change the `session.commit()` to `commit_and_refresh(session, instance)`.

Having fewer context managers also makes the code easier to read and reason about.

----

We can similarly change `transaction_session_logger`. It has two differences:

1. Handles SkippedAwardError, allowing the code to continue running
2. Handles all other exceptions, by allowing the code to continue running

(1) is important, but I think the code should just raise the error instead of continuing in (2). SkippedAwardError is raised by:

* `_create_application`, called by `_create_complete_application`, which uses `transaction_session_logger`. This function is used indirectly by the commands `fetch_awards`, `fetch_all_awards_from_period`, `fetch_award_by_contract_and_supplier` 
* `_create_award`, called by `_create_complete_application` and `fetch_previous_awards`. The latter uses `transaction_session_logger`, and is set as a background task by the API endpoint `access_scheme`
* `get_borrower`, called by `_get_or_create_borrower`, called by `_create_complete_application` (see above)
* `get_documento_proveedor`, called by `_get_or_create_borrower`, called by `_create_complete_application` (see above)
* `get_award`, called by `_create_award` (see above)
* `get_source_contract_id`, called by `_create_award` (see above)
* `get_email`, called by `get_borrower` (see above)

Uses of `transaction_session_logger` where there's no chance to raise `SkippedAwardError` should be changed to `rollback_on_error`.

**Comment by yolile** [comment]
closed by #250

**Comment by jpmckinney** [comment]
#250 replaced transaction_session_logger, not transaction_session.
