### ISSUE TITLE
Review award data (stage 3)

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#25]
When I am processing an MSME application in Credere, I want to be able to review data from OCDS for the specific award, add or update information that may be incomplete or missing by checking in SECOP II before proceeding so that the FI I work for can be confident that the process has been followed correctly.

- Link to each award in SECOP II directly
- Fields where data is missing to have an expand feature for the user to view more information and guidance on how to proceed
- Fields where data is missing or incomplete to have the option for the user to add or edit manually
- No verification toggle switch for this stage of the process

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=107-364&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closing as completed
