### ISSUE TITLE
Review past public sector awards for MSME (stage 3)

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#26]
When I am processing an MSME application in Credere, I want to be able to view past public sector contracts that the MSME was awarded and fulfilled along with the contract value amount, so that I can increase my confidence in the MSME’s ability to fulfil the contract. Include OCDS fields: 

- tender/title
- buyer/name
- contract/period/startDate
- contract/period/endDate
- contract/valueAmount in UI
- tender/status

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=430-3577&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
The detail on how to access past contracts is [here](https://docs.google.com/document/d/1ZtHcZKJfp9HIxa6HR6o1SrzTJ7schu4Pu8vGdFToSVA/edit#heading=h.986i6b4xzz5h).

Note that we should collect this information per MSME after the MSME accepts to opt into the scheme.

**Comment by yolile** [comment]
Closing as completed
