### ISSUE TITLE
Change how we get new contracts

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#273]
Currently, we use https://www.datos.gov.co/Gastos-Gubernamentales/SECOP-II-Contratos-Electr-nicos/jbjy-vk9h
With 
- es_pyme= 'Si'
- estado_contrato = 'Borrador'
- localizaci_n = 'Colombia, Bogotá, Bogotá'
- ultima_actualizacion >= {last updated date}

However, for the past month or so the ultima_actualizacion combined with estado_contrato = 'Borrador' fields are no longer being set correctly by the source. After some testing, I think we can use: 

estado_contrato not in ("Cancelado", "Cerrado", "cedido") instead. We might have some duplicates but the code will skip them anyway.

**Comment by jpmckinney** [comment]
Are we storing the `estado_contrato` anywhere, so we can later review which ones passed the condition?

**Comment by yolile** [comment]
Yes, at `award.source_data_contracts->>'estado_contrato'`

**Comment by jpmckinney** [comment]
Cool, I see:

```
# SELECT COUNT(*) c, source_data_contracts->>'estado_contrato' v FROM award GROUP BY v ORDER BY c DESC;
  c   |      v       
------+--------------
 1772 | Borrador
 1290 | En ejecución
 1097 | Modificado
  905 | terminado
  541 | Activo
  530 | Cerrado
   12 | Suspendido
```

**Comment by yolile** [comment]
Ah, yes, because some of them were previous awards (see the `previous` field). But I've added "terminado" and "suspendido" to the exclusion list
