### ISSUE TITLE
Change the "pre-approved" wording

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#275]
To something even less binding than "pre-approved"

**Comment by sebasdocp** [comment]
@yolile vamos a usar "pre-calificación" y todas sus variaciones:

Presente
- (yo) precalifico
- (tú / vos) precalificas / precalificás
- (él / usted) precalifica
- (nosotros) precalificamos
- (vosotros) precalificáis
- (ellos / ustedes) precalifican

Referencia: https://www.conjugarverbo.com/index.php?p=precalificar
