### ISSUE TITLE
Approve or reject applications (stage 5)

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#28]
When I have completed all of the checks for the MSME credit application, I want to be able to review the conditions for the credit being offered and come back to the tool once we have completed our own compliance checks internally and update the Credere system with a report and additional comments.

- User to select ‘Approve’ or ‘Reject’ for the application for the process to be marked as such
- Request FI to provide reason for rejecting application via pop up feedback box
- Provide feedback to the FI that their decision has been recorded (approved/rejected)
- Approve action to trigger an email to the user congratulating them and with next steps i.e. get contract signed
- Reject action to trigger an email to the user informing them

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=107-876&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=440-2541&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=159-1187&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=202-1766&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closing as completed
