### ISSUE TITLE
Backend configuration to filter SMEs applications according to FI's geographical area of operations (Interactuar)

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#284]
A FI expressed interest in joining Credere but they only offer credit products to certain cities in Colombia. 
To support this and filter credit products we need to add `location` to credit_product and then, to ease comparison, also `location` to `borrower`, and then update `credit_product_options` to check for that rule.

**Comment by jpmckinney** [comment]
Closing as FI unresponsive.
