### ISSUE TITLE
Signed contract review

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#29]
When the MSME uploads the signed contract with the buyer, I want to receive an email notification that this has happened and review the contract in Credere, so that I can see for myself that the MSME has definitely secured the work and what the contract value is before disbursing the funds.

- No specific details about the MSME or contract information to be in the email notification
- FI user can download the contract from the Credere UI and click on a link to view in SECOP IF available
- The contract amount can be different to a the award amount and so the FI can change the amount of credit offered to the MSME
- FI to close the loop and complete the application by clicking “Credit ready”
- FI to have the option to download the application

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=430-3390&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=430-3457&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closing as completed
