### ISSUE TITLE
Incorrect statistics

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#309]
Sebastian reported not seeing an application to an FI in the dashboard.

`update_statistics` is added as a background task after some requests (in addition to being run once a day).

Either the background task call is missing from some relevant endpoints, or the results are incorrect.

@yolile updated with: "I've checked and the task is being called but the results are incorrect for the FIs statistics, I need to double-check what is happening with the queries"

**Comment by yolile** [comment]
I see that the statistics are correct now, so maybe it was a temporary issue due to, as you said, missing calls to update_statistics
