### ISSUE TITLE
Offer at award stage only

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#31]
When I have been given an award, I want to automatically receive a notification for access to the credit scheme, so I can accept or reject the offer.

- Email notifications to only be sent to companies that have won an award in SECOP
- Companies must be registered as SMEs in SECOP

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=109-4252&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=621-3999&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
The detail on how to access and search for new awarded MSMEs is [here](https://docs.google.com/document/d/1ZtHcZKJfp9HIxa6HR6o1SrzTJ7schu4Pu8vGdFToSVA/edit#heading=h.rf7s9xvrs9t3).

**Comment by yolile** [comment]
Note some logic to follow at https://github.com/open-contracting/credere-backend/issues/10#issuecomment-1544501066


> When we check for a new awarded MSME:
> - Use the same hashing algorithm to check if this MSME already has a row in the MSME table, if so, then refill the name and identifier columns and
> - To avoid emailing the same MSME for the same award, use the same hashing algorithm with the MSME identifier and award identifier to check if that already exists in the application table. If it exists, then ignore the award as it has been processed already, if not, proceed as usual.
