### ISSUE TITLE
Serve email assets (images, etc.) from CDN (e.g. AWS)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#310]
Right now, images (referenced by the templates stored in this repository) are routed to port 8000 which proxies to credere-frontend.

Each email loads 8 images, and during mass-mailings, we can receive a lot of traffic at once. (Either lots of emails are being opened, or lots of email clients are pre-loading images.)

Offloading traffic from emails to a CDN might avoid some OOM errors that we've observed in Apache's error.log.

I think we went with linked images, because [all other options](https://mailtrap.io/blog/embedding-images-in-html-email-have-the-rules-changed/#Choosing-a-method-of-putting-an-image-in-an-HTML-message) had worse downsides.

We can do this in a forward-looking way only. Existing emails can continue to send traffic to our server. The main concern is new traffic around mass-mailings. We don't expect old, re-opened emails to cause an issue.

**Comment by jpmckinney** [comment]
@yolile I think it would be prudent to resolve this issue before sending more emails with `fetch-all-awards-from-period`

**Comment by yolile** [comment]
Sounds good. Do we have a CDN set up already that I can use?

**Comment by jpmckinney** [comment]
We probably need to set up AWS Cloudfront, and then change the image URLs to Cloudfront URLs

**Comment by jpmckinney** [comment]
> Origin request policy: AllViewer - maybe need to override Host header?

Okay, so setting "Origin request policy" to None fixes the issue.

**Comment by jpmckinney** [comment]
And now custom domain works, e.g. https://cdn.credere.open-contracting.org/images/facebook.png

As usual, please test sending an email on the dev server before committing to the CDN for thousands of emails :)

**Comment by yolile** [comment]
Thank you! It works!
