### ISSUE TITLE
Terms and conditions and privacy policy

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#32]
When I receive an email notification for the access to credit scheme, I want to be able to view the terms and conditions and privacy policy information, so I can view the finer details of the scheme and how my data is managed.

- Provide a link to a terms and conditions document online 
- Provide a link to a privacy policy document online
- These documents need to be for the Credere tool covering all FIs who partner with us for the tool
- Mandatory checkboxes for users to tick before continuing

Design TBD

**Comment by yolile** [comment]
Closing as this was implemented already, and we just need to update the texts
