### ISSUE TITLE
MSME option to opt out of the scheme

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#33]
When I receive an email notification for the access to credit scheme, I want the option to opt-out so that I am not contacted in the future.

- Opt-out user journey includes a request for feedback on why they declined the offer for access to credit
- User journey to clarify if opt-out is for this award or for all time
- MSMEs that select opt-out be removed from the mailing list as per their request (all time / this award)
- No personal data for the MSME opting out is to be collected - we only want a count of MSMEs that opted out, feedback forms completed and reasons (see Figma UI design) for opting out as per the feedback form. Instead, we will store the identifier for the MSME so as not to “forget” they have opted out

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=109-4252&t=ZGzh5x7zMAwvmP8g-4
https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=621-3999&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Moving back to backlog as this is not working yet, as per reported in #87

**Comment by yolile** [comment]
Closing as completed
