### ISSUE TITLE
Why do borrower sizes and genders need to strip " ?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#334]
From 13b0e80966a443327e60d9c8558ae889696b1c3b

I haven't tested without. Maybe it's not needed.

**Comment by yolile** [comment]
Size is added via the application form, so no needed for sure. For gender, I checked the database and we don't need to strip either (no leading or trailing whitespace found in `source_data_contracts->>'g_nero_representante_legal'`)
