### ISSUE TITLE
Do "count distinct by size" statistics need to join awards?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#335]
I think it is a copy-paste error. 

* accepted_count_distinct_by_size
* submitted_count_distinct_by_size
* approved_count_distinct_by_size

Since there is a `distinct` call, I think the `join` ends up having no effect, since the join just adds non-distinct rows.

originated in 13b0e80966a443327e60d9c8558ae889696b1c3b and kept in https://github.com/open-contracting/credere-backend/commit/d6b543e2822370ffc30ab4fd3528e468fc5d43af#diff-472af7cf72458a43f344b3f855c10ea1ce0c8fa285518a21d58686f7bb4fe80eR525

---

Same for these, which group by Application or Borrower id:

* accepted_count_unique https://github.com/open-contracting/credere-backend/commit/91f4ff7c009ad7fbc52ec1e61449160cba68e26d#diff-472af7cf72458a43f344b3f855c10ea1ce0c8fa285518a21d58686f7bb4fe80eR319
* approved_count https://github.com/open-contracting/credere-backend/commit/91f4ff7c009ad7fbc52ec1e61449160cba68e26d#diff-472af7cf72458a43f344b3f855c10ea1ce0c8fa285518a21d58686f7bb4fe80eR327

**Comment by yolile** [comment]
Yes, you are correct, I don't think we need to join awards.
