### ISSUE TITLE
proportion_of_submitted_out_of_opt_in uses borrower_submitted_at

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#337]
The variable is named application_accepted_query, so borrower_accepted_at would have been expected
https://github.com/open-contracting/credere-backend/commit/10c95705b541101310b96ba4083594fe136f101e

Not sure if the variable name is incorrect, or the field.

For #333 I assume the variable name is incorrect.

**Comment by yolile** [comment]
Yes, in the front end we refer to it as proportion of submitted, so the variable name is incorrect
