### ISSUE TITLE
accepted_count_by_gender and sector_statistics use `Borrower.size != BorrowerSize.BIG` but this is not set if only accepted

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#338]
https://github.com/open-contracting/credere-backend/commit/91f4ff7c009ad7fbc52ec1e61449160cba68e26d#diff-472af7cf72458a43f344b3f855c10ea1ce0c8fa285518a21d58686f7bb4fe80eR451

**Comment by yolile** [comment]
Correct, they shouldn't use `base_count_by_gender_query`
