### ISSUE TITLE
msme_approved_count_woman is consistent with msme_approved_count, but not with msme_accepted_count_woman and msme_submitted_count_woman

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#339]
Added in https://github.com/open-contracting/credere-backend/commit/91f4ff7c009ad7fbc52ec1e61449160cba68e26d

If I'm reading correctly, then msme_approved_count_woman and msme_approved_count_woman count the number of approved APPLICATIONS to MSME borrowers.

Whereas, msme_accepted_count_woman and msme_submitted_count_woman count the number of BORROWERS who are woman-owners of MSMEs, who accepted/submitted at least one application.

If this is clear in the frontend, then we can just add a comment to explain the difference in logic.

**Comment by yolile** [comment]
Yes, your interpretation is correct and this is how this info is displayed in the front end. I will add a comment

**Comment by jpmckinney** [comment]
I added the comment now
