### ISSUE TITLE
Unique temporary link for each MSME award

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#34]
When I opt-in for the access to credit scheme via the email notification, I want to be taken to the screen via a unique temporary link, so that  I can start my personalized application with details of the specific award that I have won populated in the tool.

- A link is for each MSME award i.e., if an MSME wins 3 awards, they receive three different links
- Link to expire after a certain period of time of not used (time limit TBD)
- Link can not be reused after an application to a bank has been submitted
- Add some content to explain to MSMEs that they can only use the link for a set period of time e.g. 1 week
- [x] #62

**Comment by yolile** [comment]
Moving back to Backlog , because "Link can not be reused after an application to a bank has been submitted" is not working as per reported in #87

**Comment by yolile** [comment]
Closing in favor of #87.

Note that this was implemented by controlling the access via the frontend and not actually expiring the link in the backend
