### ISSUE TITLE
send_upload_contract_confirmation should not set to_msme=False

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#348]
Original error in ba14fda70731431b54bab8494c45703eae271b6b

**Comment by yolile** [comment]
Ah correct, but before https://github.com/open-contracting/credere-backend/commit/bb364e3e0f88ca2e04150503a27eb26ec00ce733 this was sending emails to lender emails anyway (so no harm has been done e.g. sending emails to borrowers in dev/local testing)

**Comment by jpmckinney** [comment]
to_name is True by default so better to just delete the keyword argument, like in other functions.
