### ISSUE TITLE
Multiple options for credit

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#35]
When I input the data for how much credit I require, the repayment term and repayment start date, I want to receive multiple options for credit by different FIs that are part of the scheme, so that I can compare the costs.

- UI is designed so that MSMEs can compare the different options
- User only allowed to select and apply for one option
- Calculation for each option are based on a set of rules to be agreed with each FI and set up in the system by a OCP admin
- The calculator is to update when a user inputs or changes data in any of the fields and clicks the submit button.

**Comment by yolile** [comment]
Closing as completed
