### ISSUE TITLE
UNEXPIRED scope is probably used more often than necessary

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#351]
Once an application is accepted, its expired_at is cleared #350.

Endpoints where it makes sense:

- /applications/uuid/{uuid} (I think this is used for rendering applications in any state?)
- /applications/decline
- /applications/rollback-decline
- /applications/decline-feedback (that said, maybe we want to accept feedback after the expiry date?)
- /applications/access-scheme

Endpoints where it's not necessary because the status is ACCEPTED:

- /applications/credit-product-options
- /applications/select-credit-product
- /applications/rollback-select-credit-product
- /applications/confirm-credit-product
- /applications/rollback-confirm-credit-product
- /applications/submit

As part of this, I noticed that `/applications/upload-document` has no limit on application status. Not sure in what scenarios this endpoint should be accessible.

**Comment by yolile** [comment]
> As part of this, I noticed that /applications/upload-document has no limit on application status. Not sure in what scenarios this endpoint should be accessible.

It should be accessible when the status is: ACCEPTED, INFORMATION_REQUESTED, APPROVED
