### ISSUE TITLE
Switch to gettext

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#356]

**Comment by yolile** [comment]
I was trying to remember (and trying to find documentation about it) but I think this relies on the same strings existing in the front end so that the strings are pushed by the front end and only consumed by the back end (which is not good)

**Comment by jpmckinney** [comment]
Okay, should we just set up gettext with a local `locale/` directory like in the registry? This will help me finish #357

**Comment by yolile** [comment]
> Okay, should we just set up gettext with a local locale/ directory like in the registry? This will help me finish https://github.com/open-contracting/credere-backend/pull/357

Sounds good to me
