### ISSUE TITLE
Field validation for calculator fields

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#36]
When I input the data for how much credit I require and the repayment term, I want to be told if the values I have entered are valid, so that I can easily correct them and stay within the limits for what can be offered to my business.

- Validation needs to be one rule for all FIs, otherwise the design will not work at all
- Add content in the UI describing limits for what the user can input
- Include field validation for fields showing errors
- Add option for MSME to select what size of company they are (natural person, micro, small or medium) for relevant credit options
- Add a question for the MSME’s sector → does this impact the credit offered? Can we get from SECOP?
- Pre-populate the fields with data to get the user started and also to automatically provide credit options in the table 
  - Credit amount → add 90% of award value
  - Repayment terms → add 1 year, 0 months
  - Repayment start date → add 1 month from contract start date

**Comment by yolile** [comment]
Closing as completed
