### ISSUE TITLE
Mismatches between frontend and backend

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#374]
* [ ] suspicious_email added to frontend but not backend. open-contracting/credere-frontend@0564f9a9 `ApplicationDeclineFeedbackPayload` needs to be updated.
* [ ] IAward has source_last_updated_at and previous, but AwardUpdate does not.

**Comment by yolile** [comment]
> IAward has source_last_updated_at and previous, but AwardUpdate does not.

Ah, but none of them are actually used in the front end so I will remove them from there.
