### ISSUE TITLE
Update all emails based on new designs

### ISSUE THREAD

**Issue by sebasdocp** [open-contracting/credere-backend#375]
[Link](https://www.figma.com/design/JwGmUUXANwJhFxQlhsIm2q/Email-final-design?node-id=0-1) to **Figma** file with new designs

**Comment by jpmckinney** [comment]
@yolile Not sure if you started already, but if not it would be best to review and merge #357 first, because it changes templates (to use `LENDER` instead of `FI`).

**Comment by yolile** [comment]
Not yet, thanks for the heads up

**Comment by yolile** [comment]
Blocked by #186 which will need email redesign too
