### ISSUE TITLE
Is is_msme default=True still a good default?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#379]
In `BorrowerBase`

**Comment by yolile** [comment]
The default needed to be True when we first introduced this field as all the existing rows were is_msme=True. Currently, the value is always set when querying the data source and as Credere was conceived by MSME only I think is fair to leave it as True. But I'm open to hearing your thoughts.

**Comment by jpmckinney** [comment]
Sounds good, I just added a short comment.
