### ISSUE TITLE
Lenders: notification preferences

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#385]
Right now, each lender has a field to set up an email when all notifications will be sent. This was developed with the idea that lenders would set up a group email to receive notifications for Credere. However, that is not the case for some lenders, who want to receive notifications in all the Credere's users' emails. And other lenders don't want to receive notifications at all. 

Options:
1) Allow a comma-separated email list in the lender form
2) Send emails to each lender user instead of the lender's main email

And for lenders who don't want to receive notifications at all, create a bool field e.g. "notify_me" per user or lender, and only send notifications when notify_me = True

cc @sebasdocp

**Comment by jpmckinney** [comment]
Planning ahead, maybe an `notification_preferences` dict, where the key is a MessageType and the value is a bool. That way, in future, we can allow for enabling/disabling specific message types.

**Comment by yolile** [comment]
Sounds good, so the changes are:
- Remove email_group from Lender
- Add `notification_preferences` to User
- Change sending emails to lenders logic to check `notification_preferences` and users' emails instead of `lender.email_group`
- Change the lender and user form in the front end to remove `lender.email_group` and add `notification_preferences`

**Comment by jpmckinney** [comment]
email_group is still used in the Application_credit_disbursed template, as the "general contact" email address for the lender.

**Comment by yolile** [comment]
Ah, good catch. We can keep that field in that case, I guess.

**Comment by jpmckinney** [comment]
I don't know where to document this, but in general I think it's a good idea to agree on new model fields and API endpoints, since they are harder to change later. Other changes can be committed without coordination.

**Comment by yolile** [comment]
Implemented the back end part and will edit the front end when I'm back. In the meantime will update the database directly for our lender's current preferences.
