### ISSUE TITLE
Unused model fields

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#388]
Are these planned for future use?

- Lender
  - status
  - deleted_at
- User
  - language

I'm also not really sure what `Lender.type` affects on the frontend.

**Comment by yolile** [comment]
> Lender status, deleted_at

I guess these fields would be useful if we ever need to offboard a Lender

> User language

We are not using this one at all, as we select the language depending on the front-end request


> I'm also not really sure what Lender.type affects on the frontend.

It is part of the lender on boarding form, but we are not using it for something in particular at the moment

**Comment by jpmckinney** [comment]
Ok, I'll just document them as unused. In future, we might just drop them in a migration.

I also notice that it's a bit weird that `Lender.logo_filename` refers to a file that is stored in git in credere-frontend... It would make more sense to store the logo as bytes in the DB.

**Comment by yolile** [comment]
> I also notice that it's a bit weird that Lender.logo_filename refers to a file that is stored in git in credere-frontend... It would make more sense to store the logo as bytes in the DB.

Of course, see https://github.com/open-contracting/credere-backend/issues/175
