### ISSUE TITLE
Add a search by borrower name filter in application list

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#392]
We have more applications now and people reach out to ask about their applications (both borrowers and lenders) so it would be helpful to have a filter to search for them more quickly

**Comment by yolile** [comment]
Increasing the priority of this one as one lender also requested this feature cc @sebasdocp

**Comment by sebasdocp** [comment]
Aggree

**Comment by sebasdocp** [comment]
Junto con este también necesitamos priorizar este que también nos lo pidió el lender:

https://github.com/open-contracting/credere-backend/issues/398

**Comment by yolile** [comment]
Discussed with @sebasdocp and we agreed on having one search bar that searches for these fields:

Borrower legal name
Borrower legal representative
Borrower email
Buyer name
