### ISSUE TITLE
Adicionar las siguientes dos columnas en el vie de "all applications" de la institución financiera

### ISSUE THREAD

**Issue by sebasdocp** [open-contracting/credere-backend#398]
Después de la columna "Entidad contratante" adicionar las siguientes dos columnas:

- Columna  1: Valor adjudicado en el contrato
- Columna  2: Valor de la solicitud del crédito

(Racional: dentro de Escala decidieron priorizar por valores/montos la revisión de solicitudes)

**Comment by yolile** [comment]
completed by https://github.com/open-contracting/credere-frontend/commit/ba3390ef028d8fed32dd4a3b6af6c9a7b03633ec
