### ISSUE TITLE
Cognito Integration

### ISSUE THREAD

**Issue by nahu** [open-contracting/credere-backend#40]
Using the SDK for python, include endpoints to allow the features described in #3 and #17
That includes login, logout, recover password and set initial password to activate account.

**Comment by jpmckinney** [comment]
I followed these instructions: https://docs.google.com/document/d/143GYJ8wILx7ZW1JzOFqRMIn_uAPQy3DE/edit

If you need API access, you'll need to let me know which AWS permissions are required. You maybe need more permissions for configuration than the app does for regular operation.
