### ISSUE TITLE
Add an observation to Escala

### ISSUE THREAD

**Issue by sebasdocp** [open-contracting/credere-backend#400]
**Copy:** Para uniones temporales, pueden reemplazar el certificado de la cámara de comercio por el documento que certifique la creación de la unión temporal.

**Comment by yolile** [comment]
@sebasdocp could you specify for which document is this new description for? Does this also apply to Clara?

**Comment by sebasdocp** [comment]
Para el certificado de la cámara de comercio:
Ponerlo en el copy del lugar donde se montan ese documento siempre y cuando solo aparezca para Escala (clara no trabaja con uniones temporales)
