### ISSUE TITLE
Improve email rendering in Outlook

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#409]
Apparently, the invitation email is not being rendered correctly in Outlook 
![image](https://github.com/user-attachments/assets/c1d5aaee-1a7c-4356-90af-02b43bd158d5)

For now, we should try at least for the Credere button to look better:

![image](https://github.com/user-attachments/assets/53ed90f3-e589-4623-8a45-f0eddfe5f868)

**Comment by jpmckinney** [comment]
We can see if we can replicate the issue in Mailtrap (has a free tier).

**Comment by yolile** [comment]
Aha, also I'm using https://premailer.dialect.ca/ to at least see CSS compatibility with different email clients

**Comment by yolile** [comment]
For the button to be displayed properly, I think we need to replace the "display" CSS style

**Comment by yolile** [comment]
Weight and height attributes are also not well supported in Outlook, so I will remove them and make images smaller directly instead (note that we will need to update Cloudfront)

**Comment by jpmckinney** [comment]
Cool - are there any other tools you use? We can add them to the docs.

**Comment by yolile** [comment]
>  Cool - are there any other tools you use? We can add them to the docs.

That is the only one I found that solved my problem (checking what wasn't working per email client), and you do not need to register or pay for it.

**Comment by yolile** [comment]
Closed by https://github.com/open-contracting/credere-backend/commit/9dc088d6fd42de2255d5025adbf88d9d16a77790

**Comment by yolile** [comment]
And https://github.com/open-contracting/credere-frontend/commit/61d879386541fb7379ea2444b8781eac1d80019f in the front end (already invalidated the cache in CloudFront too)
