### ISSUE TITLE
Additional comments logic

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#412]
https://github.com/open-contracting/credere-backend/blob/097c31de0bdfd00d19a779de5ffc9711453290e9/app/mail.py#L82-L90

This means that if the lender has a `default_pre_approval_message`, then they can never send custom additional comments. Is that the intended logic, or should lenders be able to override the default?

Commit: 296f8c5ffed9d89d7ddfcf7ab9649bc50b3df6fa

**Comment by yolile** [comment]
> Is that the intended logic

Yes, that is intentional
