### ISSUE TITLE
Allow lenders to lapse applications

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#425]
When borrowers are unresponsive after a certain time, lenders should be able to lapse applications

cc @sebasdocp

**Comment by jpmckinney** [comment]
Once we implement #427, I assume this option will only be available in that flow? Or, do lenders who do the INFORMATION_REQUESTED flow need an additional way to lapse borrowers, besides the automated one?

**Comment by yolile** [comment]
Hmm, good question. I think right now they are not using the information request feature, but manually calling, etc the borrower to submit extra documents. I will double-check with Sebastian if the information requested flow and auto lapse option would fulfill this need

**Comment by yolile** [comment]
Closed by #445 and https://github.com/open-contracting/credere-frontend/pull/155
