### ISSUE TITLE
Lender additional configuration: external on boarding process and require documents

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#427]
Some lenders have their own system with their own onboarding process where borrowers must upload their documents. In these cases, the lender does not review documents in Credere, but asks borrowers to start the onboarding process in their system instead.

To facilitate this process, Credere, when an application is APPROVED and the selected lender has the "default_additional_comments" set, sends the link to the onboarding platform as part of the APPROVED email, using the default_additional_comment field. 

To make this process more general, we could add a string field, "external_onboarding_url" and a boolean field, "require_documents" to `Lender`, and remove "`default_additional_comments`".

As part of #186, if "external_onboarding_url" is set, we will have a custom email template that uses that field and asks the borrower to start the onboarding process with the lender's system when the application is SUBMITTED.

Additionally, if `require_documents` is false, we won't require the borrower to submit any documents as part of their application. (or we could also rely on the external_onboarding_url field, assuming that when an onboarding system exists, they won't need to upload documents in Credere. We only have one case so far and that is the case, so if we want to save one field we could assume that is true until we see the opposite)

I also thought about having a general "`additional_settigns`" JSONB field instead, but maybe one field with a clear use case is better.

@jpmckinney any feedback is welcome
(I will be implementing this as part of #186)

**Comment by jpmckinney** [comment]
If possible, I think it would be clearer to implement #186 separately.

---

I think we can leave out `require_documents` field for now and assume it is false.

Yes, individual meaningful fields is better.

Does the application just end with `SUBMITTED` if `external_onboarding_url` is set, or does the lender come back to change its status?

**Comment by yolile** [comment]
> Does the application just end with SUBMITTED if external_onboarding_url is set, or does the lender come back to change its status?

The lender comes back to change the status either to APPROVED or REJECTED (with STARTED in the meantime), as usual.

**Comment by yolile** [comment]
> I think we can leave out require_documents field for now and assume it is false.

Assume false If `external_onboarding_url` is set, do you mean? Because the other lender that we have (that works without an onboarding process) will require documents as usual.

**Comment by jpmckinney** [comment]
>> I think we can leave out require_documents field for now and assume it is false.
>
>Assume false If external_onboarding_url is set, do you mean? Because the other lender that we have (that works without an onboarding process) will require documents as usual.

Yup!

>> Does the application just end with SUBMITTED if external_onboarding_url is set, or does the lender come back to change its status?
>
>The lender comes back to change the status either to APPROVED or REJECTED (with STARTED in the meantime), as usual.

Ok, so, if I understand, on the new path:

1. As usual, borrower submits the application (SUBMITTED).
    *  As usual, email is sent to lender to start the application.
    * **NEW:** Email is sent to borrower containing `external_onboarding_url`.
2. As usual, lender starts "reviewing" the application (STARTED).
3. As usual, lender approves (APPROVED) or rejects (REJECTED) the application.
4. **NEW:** Lender *cannot* request information (INFORMATION_REQUESTED).
