### ISSUE TITLE
Create email templates

### ISSUE THREAD

**Issue by nahu** [open-contracting/credere-backend#43]
These are the templates to implement as plain HTML to configure SES with them.
SES Docs > https://docs.aws.amazon.com/ses/latest/dg/send-personalized-email-api.html
The images in the email should be uploaded in the S3 public bucket. They should also be stored in the repo.

Template designs
- [x] New application OCP admin: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=442-3117&t=ZGzh5x7zMAwvmP8g-4
- [x] Overdue application OCP admin: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=472-3181&t=ZGzh5x7zMAwvmP8g-4
- [x] New application FI user: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=424-2388&t=ZGzh5x7zMAwvmP8g-4
- [x] Overdue application FI: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=440-2492&t=ZGzh5x7zMAwvmP8g-4
- [x] * New Account Created: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=559-3795&t=ZGzh5x7zMAwvmP8g-4

**New templates**
- [x] Intro MSME: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=109-4252&t=QGR0qFQ8sCalhTlO-4
- [x] Intro responsive https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=621-3999&t=QGR0qFQ8sCalhTlO-4
- [x] Intro MSME reminder: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=159-937&t=QGR0qFQ8sCalhTlO-4
- [x] Complete app reminder MSME: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=159-1064&t=QGR0qFQ8sCalhTlO-4
- [x] Contract upload confirmation: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=423-2335&t=QGR0qFQ8sCalhTlO-4
- [x] Change Email MSME: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=375-2674&t=QGR0qFQ8sCalhTlO-4
- [x] Submission completed: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=466-3093&t=QGR0qFQ8sCalhTlO-4
- [x] Application Aproved: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=199-1619&t=QGR0qFQ8sCalhTlO-4
- [x] Upload contract: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=422-2110&t=QGR0qFQ8sCalhTlO-4
- [x] Application declined: https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=201-1723&t=QGR0qFQ8sCalhTlO-4

**Comment by adrianosvaldomartinez** [comment]
Python AWS SDK  to be used
https://docs.aws.amazon.com/ses/latest/dg/send-an-email-using-sdk-programmatically.html

**Comment by jpmckinney** [comment]
Is it necessary to upload to S3? I am fine with serving them from the same container as the frontend.

**Comment by adrianosvaldomartinez** [comment]
its not necessary, it  was just an option, we will serve it from the same URL as the front, as you mention, so we dont compromise any sensitive data in S3 .

**Comment by adrianosvaldomartinez** [comment]
@yolile,
In the Figma templates for the emails, we have the phrase 'View this email in your browser' above the header. 
What is the expected functionality for this? 
Is it meant to serve a webpage with the same content, or does it serve another purpose?
Thanks!

**Comment by jpmckinney** [comment]
cc @sabahfromlondon

**Comment by yolile** [comment]
> Is it meant to serve a webpage with the same content

Yes!

**Comment by adrianosvaldomartinez** [comment]
@nahu lInk al PR
https://github.com/open-contracting/credere-backend/pull/48

**Comment by yolile** [comment]
Closing as completed
