### ISSUE TITLE
SES Integration

### ISSUE THREAD

**Issue by nahu** [open-contracting/credere-backend#44]
Consider [this issue](https://github.com/open-contracting/credere-frontend/issues/4) setting up an env variable with the default value **en** if not defined.
Refactor register and forgot-password endpoints to use this utility.

**Comment by jpmckinney** [comment]
In terms of deliverability monitoring, for another project, OCP set up very simple email notifications for bounces and complaints. https://ocdsdeploy.readthedocs.io/en/latest/deploy/aws.html#set-up-notifications

If desirable, we can do something different for Credere, e.g. event publishing with configuration sets https://docs.aws.amazon.com/ses/latest/dg/monitor-using-event-publishing.html

I think you shared some suggestions, but can't find them at the moment.
