### ISSUE TITLE
Background Processes - Colombia Compra Eficiente (CCE)

### ISSUE THREAD

**Issue by nahu** [open-contracting/credere-backend#46]
Create a client for the APIs described in the [document](https://docs.google.com/document/d/1ZtHcZKJfp9HIxa6HR6o1SrzTJ7schu4Pu8vGdFToSVA/edit#heading=h.rf7s9xvrs9t3).
Use the Client to get the data and save it to the contracts and borrower database tables.
New contracts not obtained since the last time the process ran should be fetched (the last time should be the most recent creation date in the contracts table).
In case of incomplete data, notify the error through Sentry (indicate all the data of the Award/MSME to be able to identify them), and data should not be inserted if the MSME email is unavailable.
For each new contract successfully obtained, a process (dummy) must be called to create the application and send the email to the MSME.
The hashed fields to anonymously identify the Awards and MSME are indicated [in here](https://github.com/open-contracting/credere-backend/issues/10#issuecomment-1544501066)
Consider the states in #37 
The process must be callable from a CRON job at the operating system level.

**Comment by nahu** [comment]
@yolile The [API documentation](https://dev.socrata.com/foundry/www.datos.gov.co) for Contracts is missing

**Comment by yolile** [comment]
Fixed in the document, and for reference: https://dev.socrata.com/foundry/www.datos.gov.co/jbjy-vk9h

Note that, in general all the API documentations are the same as they use Socrata

**Comment by yolile** [comment]
Closing as completed
