### ISSUE TITLE
Sentry Integration

### ISSUE THREAD

**Issue by nahu** [open-contracting/credere-backend#47]
Integrate Sentry to the backend project
https://docs.sentry.io/platforms/python/guides/fastapi/

**Comment by jpmckinney** [comment]
I've sent the code via Slack. Noting that we'll also want Sentry for the frontend.

**Comment by adrianosvaldomartinez** [comment]
@nahu Link to the PR 
https://github.com/open-contracting/credere-backend/pull/51
