### ISSUE TITLE
Remove use of personal bucket in app/core/user_dependencies.py

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#57]
`adrian-personal`

Other clean up:

* `www.google.com` also used as a temporary URL.
* `print()` statements.

**Comment by nahu** [comment]
To be resolved in [logger issue](https://github.com/open-contracting/credere-backend/issues/58) and [SES utility issue](https://github.com/open-contracting/credere-backend/issues/44) ([with this](https://github.com/open-contracting/credere-frontend/issues/4))

**Comment by jpmckinney** [comment]
Noting that the staging server uses environment variables for a personal bucket, but I assume it will Just Work™ if we set our own AWS credentials.
