### ISSUE TITLE
Track FI and OCP user actions

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#6]
When a FI or OCP user logs into Credere, I want to be able to track all of the actions the user makes, so that we have a full audit trail for MSME and FI user actions, so that we can more easily address issues if they arise. For example:

- Which user added or updated data
- Which user verified information X
- Which user approved/rejected application Y
- Is processing of an application overdue Y/N

**Comment by nahu** [comment]
This is implemented with the table ApplicationActions

**Comment by yolile** [comment]
Closed as implemented
