### ISSUE TITLE
MSME User Application Endpoints

### ISSUE THREAD

**Issue by nahu** [open-contracting/credere-backend#64]
- [x] Validate Link: received the link and checks if exists, is not Started, and not expired (refer to this issue #39) 
- [x] Access the scheme endpoint
- [x] Decline Application endpoint
- [x] Upload individual document endpint: payload is file and a type.
- [x] Change email endpoint.
- [x] Confirm new email endpoint.
- [x] Submit application endpoint.

**Comment by yolile** [comment]
Closing as completed
