### ISSUE TITLE
Run an initial credit report on the business applying for credit

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#69]
For Colombia:

While the banks have to do their own risk analysis, the initial credit score review is mostly done through two companies: TransUnion & Equifax. The idea would be to do the analysis and include it as part of the application to the bank. The idea is that if a bank rejects a submission, the new bank doesn’t have to pay again for a credit report, but instead, we can share it with the next FI if the small business wants to reapply.

**Comment by jpmckinney** [comment]
Just need to be careful that it is a "soft" credit check.

> Credit inquiries are requests to check your credit. "Hard inquiries"  occur when a potential lender is reviewing your credit because you've applied for credit with them, and **may affect your credit score**. "Soft inquiries" occur when you're checking your own credit file and/or score, credit checks made by businesses **to offer you a quote**, or inquiries made by businesses where you already have an account. "Soft inquiries" do not affect your credit score.

**Comment by jpmckinney** [comment]
Closing as I think there is no demand from lenders, but can reopen if so.
