### ISSUE TITLE
Send notification for overdue application

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#7]
When a MSME application is overdue (i.e. time has gone over the SLA), I want the FI to be emailed automatically and the OCP group mailbox to be copied in, so that we are all aware of the situation and can work together to prioritise the particular application.

- User to send an email through Credere so that the application can automatically be marked as ‘Awaiting information from MSME’
- SLA for time taken to complete the application to be paused until the MSME responds
- Time taken to complete the application tracking to be resumed once information from MSME has been updated on the system
- Manual workaround for information from MSME email to be added to the system. OCP admins to be vigilant of this and not leave to the FI if they see an email first

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=472-3181&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
@nahu This hasn't been implemented yet
