### ISSUE TITLE
See all applications made to FIs

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#8]
When I log into Credere as an OCP admin, I want to be able to see all of the live applications made to the different FIs, so that I can support the application process.

- Table view with information for: MSME name, Buyer name, submission date, stage, credit provider and actions
- User to be able to sort columns (highest to lowest, lowest to highest, A-Z, Z-A), bar the actions one

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=443-3219&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closed as implemented
