### ISSUE TITLE
View but not approve

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#9]
When a MSME application is submitted, I want to be able to review and update missing data, but not have any rights to approve applications, so that the FI knows that only their own team members with the appropriate permissions can do this.

- Create a ‘role’ for OCP admins
- View and update actions in application table
- Only applications at the stages: ‘not started’, ‘in progress’ and ‘waiting for MSME’ can be updated by OCP admins
- Approved applications can only be viewed
- Completed applications can only be viewed one week after completion

https://www.figma.com/file/mQqkGtTfNEBdfk4QdfNYIO/OCP-Data-Registry-Design?type=design&node-id=443-3219&t=ZGzh5x7zMAwvmP8g-4

**Comment by yolile** [comment]
Closing as completed
