### ISSUE TITLE
Remove/replace test@mail.com

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-backend#93]
The effect of #92 is that anyone who sets up a dev environment without overriding OCP_EMAIL_GROUP will start sending email to test@mail.com, which is a real domain with MX servers.

Please either make the default value blank, or `credereadmin@open-contracting.org` – so that at least we are spamming ourselves and not some unrelated email.

**Comment by adrianosvaldomartinez** [comment]
This has been addressed in the following commit:
https://github.com/open-contracting/credere-backend/pull/88/commits/0d453978a6019c48a4b7eceaea1f372a4c14cdfc
