### ISSUE TITLE
Project structure refactoring

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#97]
To ease the code readability and follow standard practices around separating the data, business logic, and presentation layers, we should:

- ~~Rename `app` to `credere`~~
- [x] If we are going to have just one SQLAlchemy models file and one Pydantic models file, then 
  - [x] delete the `schema` package, move `schema/api.py` to ~~`schemas.py`~~ +`parsers.py` and `serializers.py`+
  - [x] merge `schema/core.py` with `schema/statistic.py` in one file called `models.py`

In the `utils` package, we are mixing business logic operations and utilities. We need to separate both concepts:

- ~~Rename the package `utils` to `services` to reflect this one is about the business logic operations, and then~~
  - [x] Rename `verify_token.py` to `auth.py`
  - [x] Move the content of `permissions.py` to `auth.py` and delete `permissions.py`
- [x] Rename `email_utility` to ~~`util`~~ +`mail`+ ~~and move `general_utils` content here~~
- [x] Delete `general_utils`

In the `backgroup_processes` package, we also mix some business logic operations. To fix this, we should:

- [x] Move the content of `application_utils` to ~~`services/applications.py`~~ +`utils/background.py`+
- [x] Move the content of `background_utils` to `util` +and `data_access/__init__.py`+
- ~~Move all the database-related methods from `awards_utils` to `services/award.py`, and the same for `borrower_utils` to `services/borrower.py`~~

Cc @jpmckinney in case you want to add something

You can implement this once the current PRs are merged

**Comment by jpmckinney** [comment]
Sounds good to me – I haven't had a close look recently to suggest any other changes.

**Comment by jpmckinney** [comment]
> Rename app to credere

I'm updating the handbook. I think `app` is actually OK, and matches FastAPI's docs: https://fastapi.tiangolo.com/tutorial/bigger-applications/#an-example-file-structure

**Comment by jpmckinney** [comment]
I think most of the `*_utils.py` methods belong on the models, since they perform basic CRUD operations, and otherwise only require a database session.

**Comment by jpmckinney** [comment]
I started a PR #198

**Comment by jpmckinney** [comment]
* [ ] Update "Repository structure" in readme
