### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#98]
Document the code as per https://ocp-software-handbook.readthedocs.io/en/latest/python/documentation.html#documentation, as per the QASP process requirement:

_Documented: High-level architecture and major functionality are documented. Public methods are documented such that tools (like phpDocumentor, JSDoc, Sphinx, etc.) relevant to the programming language can generate documentation._

**Comment by adrianosvaldomartinez** [comment]
@yolile can you provide us with the credential to read the docs so we can import the project there?

**Comment by jpmckinney** [comment]
I created the project. It fails with:

> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'docs/requirements.txt'

**Comment by jpmckinney** [comment]
If you create a ReadTheDocs account, I can add you as maintainer to be able to see build errors.

**Comment by adrianosvaldomartinez** [comment]
thanks James!, i just created one
my user name is
adrianosvaldomartinez
We haven't added the config files for it yet. We will probably do so later today.

**Comment by jpmckinney** [comment]
I've sent you an invitation to be maintainer.
